//! # Soroban Inefficient Bytes Concat Lint UI Test
//!
//! This UI test file validates the diagnostic output, warning messages, and
//! code suggestions generated by the `soroban_inefficient_bytes_concat` lint.
//!
//! ## Overview
//! Soroban smart contracts frequently need to construct or concatenate `Bytes` or
//! `BytesN` values dynamically. Performing repeated `.push_back()` or `.append()`
//! operations inside loop bodies (`for`, `while`, or `loop`) incurs heavy per-iteration
//! host call and memory allocation overhead within Soroban's metering model.
//!
//! This lint detects such performance anti-patterns and guides developers toward
//! efficient alternatives, such as accumulating data in a local Rust `Vec<u8>`
//! and converting it once outside the loop via `Bytes::from_slice`.

/// Demonstrates an inefficient bytes concatenation helper and mock module setup
/// providing minimal definitions of `soroban_sdk::Env` and `soroban_sdk::Bytes`
/// so this UI test can be compiled and verified independently without the real SDK.
///
/// # Panics
/// Does not panic; purely structured for lint verification.
fn inefficient_concat() {
    // Constructing or concatenating bytes in a suboptimal way
    let mut b = soroban_sdk::Bytes::new(&soroban_sdk::Env::default());
    b.push(1);
    b.push(2);
}
pub mod soroban_sdk {
    pub struct Env;
    impl Env {
        pub fn default() -> Self {
            Env
        }
    }

    pub struct Bytes;
    impl Bytes {
        pub fn new(_env: &Env) -> Self {
            Bytes
        }
        pub fn push_back(&mut self, _val: u32) {}
        pub fn append(&mut self, _other: &Bytes) {}
    }
}

use soroban_sdk::Bytes;

fn bad_push_back(mut b: Bytes) {
    for _ in 0..10 {
        b.push_back(1); //~ ERROR inefficient Bytes concatenation inside a loop
    }
}

#[allow(soroban_inefficient_bytes_concat)]
fn good_small_push_back(mut b: Bytes) {
    for _ in 0..2 {
        b.push_back(1);
    }
}

fn main() {
    let b = Bytes::new(&soroban_sdk::Env::default());
    bad_push_back(b);
}
